org: jfdaniel77
app: beta-motivationpods
service: beta-motivationpods

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    CONSUMER_KEY: ${param:CONSUMER_KEY}
    CONSUMER_SECRET: ${param:CONSUMER_SECRET}
    CONSUMER_TOKEN: ${param:CONSUMER_TOKEN}
    CONSUMER_TOKEN_SECRET: ${param:CONSUMER_TOKEN_SECRET}
    MDB_USER: ${param:MDB_USER}
    MDB_PWD: ${param:MDB_PWD}
    MDB_CLUSTER: ${param:MDB_CLUSTER}

functions:
  tweetMessage:
    handler: handler.run
    events:
      # Invoke Lambda function every 4 hours
      - schedule: rate(4 hours)
